from datetime import datetime

parametros = {
    'path': '/workspaces/teste_streamlit',    
}

# Lista de nomes válidos para apresentações
nomes_validos = [
    "Anderson Alencar",
    "Anderson do Vale",
    "Aparecida Spina",
    "Arileide Cristina Alves",
    "Arlene Trinco",
    "Armando Vieira",
    "Aron Stachecka",
    "Bernardo",
    "Bibiane Vieira",
    "Camila Bernardo",
    "Carina Wojcik",
    "Carlos Alberto",
    "Carlos Montesino",
    "Clarice Colaço",
    "Claudio Studzuski",
    "Daiane Almeida",
    "Daiane Graciela",
    "Daniele Colaço",
    "Daniele Rodrigues",
    "David Affonso",
    "Davides Affonso",
    "Derli Gonçalves",
    "Doris Foltran",
    "Dulce Nogueira",
    "Denise Mann",   
    "Ederson Carneiro",    
    "Edilene Silva",
    "Edson Padilha",
    "Eduarda Monteiro",
    "Elber Soares",
    "Emilly Carneiro",
    "Érica Rodrigues",
    "Esli Santos",
    "Ester Machado",
    "Eva Helena",
    "Felipe Carneiro",
    "Felipe Gobato",    
    "Fernanda Machado",
    "Fernanda Madeira",
    "Francinco Lezcano",
    "Gabriela Ribeiro",
    "Gessica Sousa",
    "Gicelle Carneiro",
    "Gilmar de Lucas",
    "Giovani Vieira",
    "Gisele Vieira",
    "Heitor Wojcik",
    "Herminio Maciel",
    "Isabela Vieira",
    "Jahina Gonçalves",
    "Jerome Sampaio",
    "João Batista",
    "José Francisco",
    "Josnei Machado",
    "Jucimere Machado",
    "Ketlin Carneiro",
    "Lara Sophia",
    "Laura Franco",
    "Lidyane Soares",
    "Luiz Nogueira",
    "Lucas Daniel",
    "Luciana Perpétuo",
    "Luís Cláudio de Júlio",
    "Luiz Eleutério",
    "Marcos Ribeiro",
    "Marcos Woicjki",
    "Maria da Luz",
    "Maria Dione",
    "Marli Carneiro",
    "Miguel Mann Bernardo",
    "Millena Carneiro",
    "Miriam Affonso",
    "Nadir Padilha",
    "Natalia Alves",
    "Nícolas",
    "Noêmia Melo",
    "Paulo Carvalho",
    "Paulo Franco",
    "Raphael Madeira",
    "Rafaela Silva",
    "Regina Fonseca",
    "Renato Horning",
    "Rosa",
    "Rose de Jesus Coutinho",
    "Roseli de Julio",
    "Roseni de Almeida",
    "Santina Gobato",
    "Sergio Santos",
    "Silmara Spina",
    "Silvana Franco",
    "Sylwia Stachecka",
    "Simone Machado",
    "Thalita Castro", 
    "Valdir Tadra",
    "Vanda Alves",
    "Yamilet Prieto Zamora",
]

def converter_data(data_str):
    return datetime.strptime(data_str, "%d/%m/%Y")